### ISSUE TITLE
Accessing keywords / about 

### ISSUE THREAD

**Issue by igrigorik** [ssoper/summarize#1]
More of a feature request rather than a bug.. But would be nice to get access to --about (since --keywords is deprecated), which simply returns the top keywords/topics for the input doc!

ex: 

ots ig1 --about
Article talks about "concurrent,models,process,threads,channels"

**Comment by ssoper** [comment]
shouldnt be too hard to implement, will do.

**Comment by ssoper** [comment]
Done (v 1.0.3)

**Comment by igrigorik** [comment]
Awesome. Thanks!
